version: 0.2


phases: 
  build: 
    commands:
       -echo Entered the build phase....
       -mvn clean package
  post_build:
    commands:
       - echo Build compleated successfully
artifacts:
   files:
     - target/Git-Aws-CodePipeline.jar
   discard-paths: yes